# Generated by Django 2.1.7 on 2019-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baozhuang',
            options={'verbose_name': '包装类型表'},
        ),
        migrations.AlterModelOptions(
            name='daozhan',
            options={'verbose_name': '到站表'},
        ),
        migrations.AlterModelOptions(
            name='fachekehu',
            options={'verbose_name': '发车客户表'},
        ),
        migrations.AlterModelOptions(
            name='guige',
            options={'verbose_name': '货物规格表'},
        ),
        migrations.AlterModelOptions(
            name='huowu',
            options={'verbose_name': '货物种类表'},
        ),
        migrations.AlterField(
            model_name='baozhuang',
            name='name',
            field=models.CharField(max_length=50, verbose_name='包装类型'),
        ),
        migrations.AlterField(
            model_name='daozhan',
            name='name',
            field=models.CharField(max_length=50, verbose_name='到站'),
        ),
        migrations.AlterField(
            model_name='fachekehu',
            name='name',
            field=models.CharField(max_length=200, verbose_name='发车客户'),
        ),
        migrations.AlterField(
            model_name='guige',
            name='name',
            field=models.CharField(max_length=50, verbose_name='货物规格'),
        ),
        migrations.AlterField(
            model_name='huowu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='货物种类'),
        ),
    ]
