# Generated by Django 2.1.7 on 2019-03-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0002_auto_20190322_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baozhuang',
            options={'verbose_name': '包装类型表', 'verbose_name_plural': '包装类型表'},
        ),
        migrations.AlterModelOptions(
            name='daozhan',
            options={'verbose_name': '到站表', 'verbose_name_plural': '到站表'},
        ),
        migrations.AlterModelOptions(
            name='fachekehu',
            options={'verbose_name': '发车客户表', 'verbose_name_plural': '发车客户表'},
        ),
        migrations.AlterModelOptions(
            name='guige',
            options={'verbose_name': '货物规格表', 'verbose_name_plural': '货物规格表'},
        ),
        migrations.AlterModelOptions(
            name='huowu',
            options={'verbose_name': '货物种类表', 'verbose_name_plural': '货物种类表'},
        ),
    ]
