# Generated by Django 2.1.7 on 2019-03-22 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0004_fache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jisuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jianshu', models.PositiveIntegerField()),
                ('zhongliang', models.FloatField()),
                ('baozhuang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tongzhidan.Baozhuang', verbose_name='包装')),
                ('guige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tongzhidan.Guige', verbose_name='规格')),
            ],
            options={
                'verbose_name': '发车数量表',
                'verbose_name_plural': '发车数量表',
            },
        ),
        migrations.RemoveField(
            model_name='fache',
            name='baozhuang',
        ),
        migrations.RemoveField(
            model_name='fache',
            name='guige',
        ),
        migrations.AddField(
            model_name='jisuan',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tongzhidan.Fache', verbose_name='编号'),
        ),
    ]
