# Generated by Django 2.1.7 on 2019-03-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0005_auto_20190322_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jisuan',
            name='zhongliang',
        ),
    ]
