# Generated by Django 2.1.7 on 2019-03-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0006_remove_jisuan_zhongliang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jisuan',
            name='jianshu',
            field=models.PositiveIntegerField(verbose_name='件数'),
        ),
    ]
