# Generated by Django 2.1.7 on 2019-03-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0008_auto_20190323_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fache',
            options={'ordering': ('-date',), 'verbose_name': '发车计划表', 'verbose_name_plural': '发车计划表'},
        ),
    ]
