# Generated by Django 2.1.7 on 2019-03-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0009_auto_20190323_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fache',
            name='date',
            field=models.DateTimeField(verbose_name='计划发车日期'),
        ),
    ]
