# Generated by Django 2.1.7 on 2019-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0011_auto_20190323_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fache',
            name='date',
            field=models.DateField(verbose_name='计划装车日期'),
        ),
    ]
