# Generated by Django 2.1.7 on 2019-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tongzhidan', '0012_auto_20190323_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fache',
            name='date',
            field=models.DateTimeField(verbose_name='计划装车日期'),
        ),
    ]
